### PR TITLE
Update mirc.md

### PR DESCRIPTION
**Pull request by a-raccoon**
Removed instructions for outdated or unmaintained scripts that reportedly no longer work.  Included instructions for newly written minimalistic script that does work.

### CODE REVIEW

**Comment by blakehawkins** [comment]
@a-raccoon you have merge conflicts

**Comment by a-raccoon** [comment]
@blakehawkins there are no conflicts if both files are merged. yeah, a non-existing file can only exist after its been pushed.  anyway, I need to edit this article again due to recent implementation of SASL spurred on by my script.

**Comment by svbeon** [comment]
Please make a new PR that is a combination of #287 and #288, so the updated article and the actual file is the same commit in the same PR

**Comment by svbeon** [comment]
Please see previous comment

**Comment by christeld** [comment]
Closing, see https://github.com/freenode/web-7.0/pull/351

**Pull request closed without merging**
