### PR TITLE
remove Irssi sasl docs in favour of linking to grawity's up to date guide

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by edk0** [comment]
I'd much rather update our guide.

**Comment by ailin-nemui** [comment]
currently the guide will leave users of modern irssi in a limp

**Comment by edk0** [comment]
@grawity could we update our irssi SASL documentation based on your guide?

**Comment by grawity** [comment]
Feel free to.

**Comment by edk0** [comment]
Will do. Thanks.

**Pull request closed without merging**
