### PR TITLE
Update copyrights

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by svbeon** [comment]
I'd rather have 2016-2017

**Comment by TingPing** [comment]
The start date is all that matters, there is no point in including a range.

**Comment by svbeon** [comment]
Yes and no, our old site had a range, and in my opinion the range provides a small piece of history, and the range may give a small piece of aliveness. But if we should do a range it should totally be templated and not updated manually every year but rather every yeah when something gets updated

**Comment by TingPing** [comment]
As long as its understood it has no legal significance (in the US at least).

**Comment by svbeon** [comment]
Might not have, I'm not a law expert. But thing is, some content were written 2016 and some 2017, thus a range is usually appropriate as it includes the copyright dates of all work on the site

**Comment by mistohise** [comment]
I expect it should either be a range incorporating all content, or there should be a specific date on each page which relates to the date of that content. Ref e.g. BBC news.

**Comment by svbeon** [comment]
That's at least how I've been told to treat it, and looking at the top two Google hit for `Copyright Range?`:
  - http://epiphany.law/articles/copyright/copyright-dates-single-year-or-range and 
  - https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html
  -  https://herbmiller.me/2014/02/07/advice-copyright-statements-extend-year-range/
So yes, personally I think range

**Pull request merged**
