### PR TITLE
Update people page, fixes #360

### LINKED ISSUE #360: https://freenode.net/people is out of date
https://freenode.net/people is out of date. I'd make a PR for it except the wording and stuff needs infra and/or HoS discussion so I'm leaving it to them.

### PR DESCRIPTION
**Pull request by emersonveenstra**
fixes #360 (edit by Swant)

### CODE REVIEW

**Comment by svbeon** [comment]
Hmm was this the actual outcome? Iirc the head of dev role was split up and ilbelkyr became head of IRCD/Services, i became head of web development and I THINK kloeri as head of infra got the responsibility of other things development related

**Comment by svbeon** [comment]
But please correct me if that has changed

**Comment by christeld** [comment]
@emersonveenstra See @svbeon's comments above

**Comment by svbeon** [comment]
fixes #360

**Comment by emersonveenstra** [comment]
yea, that looks good too, i wasn't sure if we were adding Swant and I or not

**Comment by svbeon** [comment]
@christeld then if you have the last say on the wording, merge if you don't have any complains :)

**Pull request merged**
