### PR TITLE
Change "blurb" to "description"

### PR DESCRIPTION
**Pull request by glguy**
I'm finding too many people don't know what a blurb is.

### CODE REVIEW

**Review by swantzter — APPROVED** [review]
I approve with sadness in my heart

**Comment by swantzter** [comment]
However I'm not entirely sure "description" carries the same meaning as "blurb", I might be in the wrong here but blurb to me would be more like a short description, and I don't want people writing novels when they don't have to.

Gavr you seen any confusion on that with your version?

**Comment by glguy** [comment]
@swantzter I'd be satisfied with _short description_ or _brief description_. I've been using plain _description_ for a bit now in my local copy that I was sharing before this central URL with no particular negative consequences.

**Comment by swantzter** [comment]
It's probably fine either way, just saying description has the benefit of keeping it short, which, unlike this comment, has the benefit of not being unnecessarily wordy :)

Let's use this and we can change it later if we see it causing novels

**Pull request merged**
