### PR TITLE
Registration: add instructions for finding staff

### LINKED ISSUE #492: registration help doesn't say *how* to contact staff

### PR DESCRIPTION
**Pull request by fndax**
Normally I'd mention `/stats p` instead of `/join #freenode` for obvious reasons, but the channel is actually fairly helpful for registration issues so I made an exception.

Fixes #492

### CODE REVIEW

**Comment by glguy** [comment]
Pointing people to `#freenode` sounds right to me. I've already heard people ask how they'd find a staff member in the first place. Most registration issues won't need a staff member specifically, so I think that's another win for joining the channel instead of recommending `stats p`. Of course `stats p` already confuses new users as it the destination of the output can be a surprise.

An additional comment I'd make is that we might want to tell people how to identify who is staff on `#freenode`. It might not be obvious to check for `@` or a `freenode/staff/`. Being explicit will help them know who they can trust as authoritative.

**Comment by fndax** [comment]
@glguy Would adding the following sentence to the end address your second paragraph?

> If your problem involves sensitive information, be aware that people with ops in the channel (designated with `@` and a `freenode/staff/` cloak in `/whois`) are network staff and can be messaged in private as needed.

(Bit more technical than I was hoping, but I'm having trouble thinking of better wording)

**Comment by swantzter** [comment]
For a nitpick I'd say "commonly designated by @" because not all clients does that

**Comment by down4some1x** [comment]
### 

> [_**``**_](

- 

 #@
Duplicate of #1. url
2.
)

**Pull request closed without merging**
