### PR TITLE
Revamp the jumbotron, now looking 100% more clean and 75% more epic.

### PR DESCRIPTION
**Pull request by boxmein**
Here's what the new design would look like (browser UI starts directly above the image):

show off 1

The top bar is still there - it will be shown when the user passes the splash part of the page into the blog / footer area.

### CODE REVIEW

**Comment by edk0** [comment]
This looks good to me, but we should find somewhere to put the PIA logo such that it is visible without scrolling down

**Comment by samuelnajdowski** [comment]
I agree with edk on this one. Let's make it visible to the naked eye.

**Comment by edk0** [comment]
Having looked around some more: there are some padding issues (though I assume they're dealt with by #83), and the jumbotron probably shouldn't do that on pages that aren't index.

**Comment by svbeon** [comment]
I disagree as long as the PIA logo isn't shown in a nice way

**Comment by svbeon** [comment]
II would decrease the blank space in the top of it as well, at least for @media (--max-md)

**Comment by svbeon** [comment]
Also use  instead

**Comment by svbeon** [comment]
also: how is FN logo and PIA logo going to be displayed on all pages?

**Comment by edk0** [comment]
@svbeon, the bar with those on is still there, hiding behind the jumbotron. It's visible on other pages. I think we need a jumbotron-like-thing that doesn't do this, though, for e.g. faq/index/chat

**Comment by svbeon** [comment]
@edk0 ah okay, then that's a tolerable solution, but yes we need one for the other pages

**Comment by svbeon** [comment]
merged with #107

**Pull request closed without merging**
