### PR TITLE
Adding supported OS to client list

### PR DESCRIPTION
**Pull request by silversword411**

### CODE REVIEW

**Comment by silversword411** [comment]
Possible...it was an optional addition and didn't seem to clutter the page too much so thought I'd submit it for consideration. I was recently looking for a SASL compatible IRC client to connect to freenode, and this was in the top of the google search that I found/used for consideration. The OS compatibility would have helped me :)

**Comment by svbeon** [comment]
I see, we'll take it into consideration and we'll see :)

**Comment by bigpresh** [comment]
I see the value in this, but needs to be checked for accuracy, particularly with regards to just saying "Linux" for stuff that runs on various *nix-like systems.  For instance, ZNC is shown as Linux, but it can also run on *BSD and, I believe, OSX.  Epic5, likewise, is included in, at least FreeBSD and possibly other *BSD distros, and has a Mac port.

**Comment by silversword411** [comment]
My understanding what any 'nix supported client can be compiled on either Linux or Unix (though you may not have pre-compiled binaries, you can download source and compile...I was trying to avoid going down the 27 flavor rathole. If I was mistaken, can you give me the main categories of 'ix and I'll update.

**Comment by svbeon** [comment]
Closing this in favour of much better lists if you're looking for an IRC client (such as [this Wikipedia article](https://en.m.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients)) also, this is more of a "how to set up sasl for the client you already have" than "find an IRC client that supports SASL"

**Pull request closed without merging**
