### PR TITLE
Add instructions for setting modes

### PR DESCRIPTION
**Pull request by RhinosF1**
per discussion on #freenode regarding https://freenode.net/kb/answer/channelmodes not explaining this.

### CODE REVIEW

**Comment by RhinosF1** [comment]
> Feeback on irc from e: seems good - might want to use two shorter lines

Done

**Comment by aleb** [comment]
While you are at it, please add examples of how to add a ban and how to remove it.
IIUC from the discussion earlier today:
`/mode #yourchannel +b` to list
`/mode #yourchannel +b yourmask` to add a mask
`/mode #yourchannel -b yourmask` to remove a mask

**Comment by RhinosF1** [comment]
@aleb , I'll look in to it

**Comment by RhinosF1** [comment]
@aleb, It looks like it's already mentioned in on the page. Is there any specific change.

You can make changes yourself by using the pencil when on the file page.

**Pull request merged**
