### PR TITLE
Add channel and user modes, extban and chanserv command help they depend on

### PR DESCRIPTION
**Pull request by Fuchs**
This pull request adds the following 4 pages: 
usermodes.md:  Explaining all (user visible) umodes and how to set them
channelmodes.md: Explaining all cmodes and how to set them, extban not included
extbans.md: Information about extbans, linked to from channelmodes.md
chanserv_overview.md: Information about ChanServ settings and control flags, as some of them are referenced and needed by channelmodes.md (mainly MLOCK and GUARD)

structure is as discussed in #freenode-web, feel free to move around if needed. 
Could do with some proof reading both language- and content wise.

Fixes:  #153

### CODE REVIEW

**Comment by tinyhippw** [comment]
closing as merged via #209

**Comment by svbeon** [comment]
@Fuchs would you mind updating this branch with master?

**Comment by edk0** [comment]
Closing for the reasons we discussed on IRC

**Comment by Fuchs** [comment]
For the sake of public documentation, because other users were interested in it as well, I'd rather the reasons would be mentioned here as well. Thanks.

**Comment by edk0** [comment]
okay: in its current form, this PR largely duplicates help output that's already available on IRC, and we don't want to have to maintain it in two places.

**Comment by Fuchs** [comment]
> okay: in its current form, this PR largely duplicates help output that's already available on IRC, and we don't want to have to maintain it in two places.

Sorry, but: no. Various issues with that: 

First of all, this is not the reason that we discussed on IRC at all, this is the first time that I read this. 

In addition to that: the ircd provided help isn't maintained, which is part of the reason why I wrote this page, as many users were interested in it. The ircd provided help lacks modes, lacks important information for certain modes  (e.g. how to properly maintain the +g accept list) and some information is very hard to find (e.g. extban) because it is not referenced where users are looking for it. If you merge that information into the ircd help: perfectly fine with me and an okay solution, even though I assume some users would still prefer it on the website. If the ircd help isn't maintained though, that argument doesn't really work. 

As said on IRC: sorry that this has to go through you. I'd very gladly discuss with the people who actually made this decision both here or on IRC, it adds just overhead and awkwardness to do this through messengers.

Thanks for your work and kind regards

**Comment by tinyhippw** [comment]
My 2 penneth, I agree with both of you: either the documentation should be updated, and ideally updatable without having to restart the IRCd
OR
the documentation should be done elsewhere

At the same time, there is also an argument for having no documentation, as it encourages users to speak to each other rather than the typical "How do I x?" "RTFM n00b"

I would opt for a "make people have a conversation rather than document everything" route, with everything documented from a more technical perspective, ie. people who know what they are doing and know there's a mode for that, but cant remember the exact syntax

Therefore you end up with documentation that is too technical for people who should really be asking how to do things, but provides enough information for more technically adept users to find what they need to do something they can't quite remember the syntax for. 

However whether that documentation goes in the IRCd or a website would be the next discussion point.

**Comment by Fuchs** [comment]
@tinyhippw: I'd agree on the "make people discuss". However, if I grep over #freenode, every time that discussion  (and also others) came up, the answer tended to be a rather short "/quote help umode" by both regular users and staff. So this isn't happening.  If you don't have the documentation somewhere, people will make gists as they did in the past, then you have the documentation spread over various places and then you really can't maintain it. I actually already have been asked to create a gist, which I refused with the argumentation that  1) I hate gists  2) either it is officially on freenode or it is nowhere.

**Comment by Frogging101** [comment]
I'm not technically a contributor, just an interested user. Hopefully my input is still welcome.

I don't get what is so controversial about this. It's relevant and useful information on how to use the network. One would expect to find it on the website. Yet it's been fought over for months in an apparently roundabout manner, reverted and closed multiple times for secret reasons. This isn't good open source development. Freenode is better than this.

**Comment by emersonveenstra** [comment]
It's controversial because ideally people should discuss these things rather than throw commands at people. But the latter is easier to do, and #freenode tends to have a "teach a man to fish" mentality that encourages this. Putting the information on the website will allow for community contributions and updates as well. Yes, it is in two places, but the ircd help docs range from cryptic (see ACCEPT point above) to incomplete (lack of +S cmode) to misleading (documents extbans c,o,s which are not enabled on freenode), and given the pull request for removing the leading spaces from the nickserv verify email has sat unmerged for six months and counting, I don't have much confidence those help docs will be maintained. 
All that this standoff has done is made people in #freenode (me included btw) update their aliases/triggers/etc to give a command rather than a link to a webpage. If nothing else, at least put accurate documentation on the website until the ircd help docs get updated.

**Comment by mistohise** [comment]
It wasn't reverted for secret reasons it was reverted because the content hadn't passed the approval and QC that was needed, so it should never have been merged in the first place. The original merge was a misunderstanding. The matter of where to put this stuff was still under debate last knew, but, like all things freenode, such debate happens at its own speed and there are other, frankly more pressing, priorities. If people feel that they must have different aliases so that they might be the first to rush to other's support with a potted mechanic answer, so be it.

**Comment by Fuchs** [comment]
@mistohise: The first pull and the revert isn't the actual issue, rather the reason(s) given for this revert, because without wanting to disclose all of it, there is quite a strange discrepancy between what was told to whom, when and where, and it doesn't make sense. As said, I'd happily discuss with the people who made this decision, but as so far it seemed to have been preferred that other people, who don't even share the views, do the talking. And that's odd.

As far as pressing issues go: yes, there are more pressing issues, but as emersonveenstra wrote these don't seem to be addressed either.

And as far as support goes: as said, when I do a simple grep on this specific issue over #freenode in the past months, it seems that the tincan reply is also given by staff and the wanted mentality isn't around. So with not gaining anything on that end, and on the other hand losing the possibilities for others to contribute and for projects to have a (up to date and maintained) documentation they can link to in their internal docs  (e.g. various wikis from Linux distributions) and people already starting to ask for and create gists: I really don't see anything won here.

**Comment by Gryllida** [comment]
I would update this in the ircd and not mirror it at the web site.

**Comment by bklockwood** [comment]
I too am confused and dismayed by the resistance to putting this information on the web. 

As a chanop, when I'm halfway through typing a mute or ban and I want to consult the syntax reference, last thing I want to do is backspace through what I have typed so far, type a _/quote help extban_ command, parse that, and then retype all I had typed before. Rather it would be useful to switch to a different window (my browser) and read what I need there - with nice formatting and variable width to boot.

I understand the concern about maintaining two sets of docs. Possibly some automation could be built, which duplicates one set of documentation into the other codebase. 

The 'have no docs because this encourages people to talk to one another' argument is, to be frank (but hopefully not personally insulting), asinine. What happens when someone wants to perform a particular task, but none of the people who remember that syntax happen to be asleep, away from keyboard, or busy with other tasks? You've just left some user helpless when he or she could have been trivially helped by making these pages available. 

Even in the best case where a user asks for syntax, is perfectly understood and perfectly answered in a short period of time, lack of accessible online docs denies people the ability to browse and learn new capabilities they may not previously have known existed. Removing the manual is **not** the correct solution to "RTFM n00b" attitudes.

Please, put these pages up.

**Comment by edk0** [comment]
Thanks for the feedback, all. Unfortunately GitHub has broken this PR, but we'll be reviewing it at #235 with a few to merging it soon.

**Pull request closed without merging**
